### ISSUE TITLE
kirbyup in subfolders

### ISSUE THREAD

**Issue by youngcut** [johannschopplich/kirbyup#1]
Gday. 
This: `kirbyup './site/plugins/myplugin/src/index.js' --watch` outputs the index.js to the root.
...istead of `./site/plugins/myplugin/src/`

**Comment by johannschopplich** [comment]
kirbyup assumes you are working inside a plugin's directory. I recommend working inside a plugin. But for your edge case I introduced a `--out-dir` option. See: https://github.com/johannschopplich/kirbyup/commit/1fa4854fb6220a752578065731433b458b605c65

Update to v0.12.0 to access that option. Have fun!
