### ISSUE TITLE
Bump to v1.0.0

### ISSUE THREAD

**Issue by renestalder** [johannschopplich/kirbyup#15]
I currently assume there is no reason to stay below v1.0.0. At least I don't see anything unstable with Kirby Up and therefore would recommend, or better ask, to bump the version to v1.0.0 unless there are any immediate breaking changes in the pipeline.

Staying below v1.0.0 for usage in production has a bit of a drawback: Tools that use semantic versioning to e.g., notify about updates, automatic patching and so on, rely on correct semantic versioning to be used with all their features.

Like, I use Renovate (similar tools: Dependabot) for dependency updates. Usually, minor releases in the pre 1.0.0 release are considered possible breaking changes too. Therefore, Renovate will not automatically patch my websites.

The situation gets much clearer with a v1.0.0 upwards release.

**Comment by johannschopplich** [comment]
I'd consider `kirbyup` pretty stable by now. Good catch! Let's consider this the perfect day to release [v1.0.0](https://github.com/johannschopplich/kirbyup/releases/tag/v1.0.0).
