### ISSUE TITLE
Extremely slow starts if kirbyup.config exists

### ISSUE THREAD

**Issue by jonaskuske** [johannschopplich/kirbyup#19]
When there's a `kirbyup.config.(js|mjs|...)` in a project, kirbyup takes roughly 20x as long to start building (or with #18: serving) the plugin.

Without a kirbyup config, my plugin build finishes in `~0.7s`. If a kirbyup config exists, it takes `~14s`, almost all of which is the loading of the config. I added a `console.log` to my config file – nothing happens for ages, then the config executes and is logged and shortly after the build completes.

I guess `unconfig` takes long to check all possible config paths and then compile the found config? But no matter the cause, not a great experience :(

**Comment by johannschopplich** [comment]
Yeah, I've noticed that one too when tests were still using an execution strategy with `npx tsx cli.ts`. I have no idea why it takes that long, tho. Especially, since UnoCSS for example loads configs with `unconfig` much faster. Maybe a misconfiguration from my side?

I adapted a lot of code directly from the [UnoCSS loading strategy](https://github.com/unocss/unocss/blob/main/packages/config/src/index.ts).

**Comment by johannschopplich** [comment]
Can you confirm loading a `kirbyup.config.js` is much faster with:

```js
export default {
  // ...
}
```

instead of:


```js
import { defineConfig } from 'kirbyup' {
  // ...
}
```

…?

**Comment by jonaskuske** [comment]
Confirmed!

And makes sense, Node has to load and run all of these imports just to get the `defineConfig`:

```ts
import 'node:fs';
import 'node:fs/promises';
import 'pathe';
import 'vite';
export { b as build, d as defineConfig, s as serve } from './chunks/index.mjs';
import 'postcss-load-config';
import 'postcss-logical';
import 'postcss-dir-pseudo-class';
import 'consola';
import 'perfect-debounce';
import 'picocolors';
import 'vite-plugin-full-reload';
import 'fs';
import 'path';
import 'module';
import 'crypto';
import 'zlib';
import 'util';
import 'unconfig';
import 'magic-string';
import 'detect-package-manager';
```
