### ISSUE TITLE
Use PostCSS plugins for RTL language support

### ISSUE THREAD

**Issue by lukasbestle** [johannschopplich/kirbyup#2]
In Kirby's `vite.config.js`, we use the `postcss-logical` and `postcss-dir-pseudo-class` plugins to transform CSS syntax related to RTL language support. I think it makes sense if Kirby plugins would also be able to use the same syntax for full compatibility with RTL localizations of the Panel.

**Comment by johannschopplich** [comment]
Great input, thank you!

Integrate those two plugins: https://github.com/johannschopplich/kirbyup/commit/369128688f6b174f4c55ca8fb9f626a682da970a. Available from kirbyup 0.13.0 onwards.
