### ISSUE TITLE
Vue is not defined (dev + build)

### ISSUE THREAD

**Issue by SamuelRiversMoore** [johannschopplich/kirbyup#24]
Hello, I have a issue that looks similar to #8 but which also happens during the `dev` process and with another library. 

One year ago I have made a panel field plugin which uses some of the components provided by [vue-grid-layout](https://github.com/jbaysolutions/vue-grid-layout). At that time I did the plugin compilation with Parcel 1 and it worked, but now Parcel 1 seems to be obsolete and I cannot make it work with Parcel 2. 

So I thought I could use Kirbyup to do it as it seems to be simpler, but I am struggling to make it work either.

There is a `Vue is not defined` error which is thrown in the browser console during dev or after a build process.

Like for Sylvain, the error is related to the following line from the compiled js file : 
```(...) window.panel.plugin("samrm/dda-mosaic",{fields:{mosaic:_n},blocks:{mosaic:ri}})})(Vue);```

It seems Vue is imported somewhere inside `vue-grid-layout` which breaks the process, but I don't think any call to `Vue.extend` is in use here. 

Any idea on how to handle this issue? Does it make sense to try to adapt the patch you provided to Sylvain (which seems to be designed specially for the build process)? 

Thanks!

**Comment by SamuelRiversMoore** [comment]
If I may add : `vue-grid-layout 2.4.0` is installed as a dependency and the `GridLayout` and `GridItem` components are imported from `vue-grid-layout` inside a wrapper component which is used for the panel field.

**Comment by johannschopplich** [comment]
Seems like the `vue-grid-layout` library imports Vue to use it [as an EventBus](https://github.com/jbaysolutions/vue-grid-layout/blob/master/src/components/GridLayout.vue#L158). Since Vue is imported in the library, kirbyup will externalize it. 
A cleaner solution would be to use a library like [mitt](https://github.com/developit/mitt) for the EventBus, instead of initializing Vue. The latter one was/is common in Vue 2 contexts. Vue 3 dropped this feature.

Nevertheless, a fix would require changes to the `vue-grid-layout`. You could duplicate the components of the library and replace the EventBus with another library.

**Comment by SamuelRiversMoore** [comment]
> Nevertheless, a fix would require changes to the vue-grid-layout. You could duplicate the components of the library and replace the EventBus with another library.

Indeed, thank you for the advice! I imported a custom version of the library, using `mitt` as eventBus and it works well.

 > I don't know how Parcel handled this behavior. Maybe it bundled Vue itself into the Panel build? How big was your bundle?

The previous build with Parcel v1 was `230kb`, now with kirbyup and without the Vue import it weights `131kb`!

Thank you again for your help!

**Comment by johannschopplich** [comment]
I appreciate you took the time to refactor the library. Occasionally I give tips on how to implement something in an issue, which then doesn't happen because of the effort involved for the person asking. Glad to know that the effort for myself writing the answer was worth it!

**Comment by jonaskuske** [comment]
FWIW, I've raised the core issue – Kirby exposing the Vue constructor only via `use` so plugins can't target it – in https://github.com/getkirby/kirby/issues/4735. Aside from the occasional compat issues we have like this one or https://github.com/johannschopplich/kirbyup/issues/8, the way Vue is provided right now also completely prohibits using Vue 2.7 functionality like dynamic CSS variables or `setup` functions :(

**Comment by SamuelRiversMoore** [comment]
Great! Thank you so much for raising that discussion up!
