### ISSUE TITLE
HMR throws error in Kirby 3.8.3

### ISSUE THREAD

**Issue by johannschopplich** [johannschopplich/kirbyup#33]
Originally reported by @CrisGraphics in https://github.com/getkirby/kirby/issues/4907.

When saving a Vue component while running `npm run serve`, the following error is thrown in the Panel:

> `usedComponentDefs[componentName] is undefined`

The error will occur with the panel starter kit. @jonaskuske would you mind, taking a look? It's probably related to https://github.com/getkirby/kirby/pull/4820 and https://github.com/getkirby/kirby/pull/4884/files. Thank you. 🙂

**Comment by CrisGraphics** [comment]
Thanks Johann, 
You were quicker than me opening the issue here. =)
Also, many many thanks (and to @jonaskuske as well) for integrating HMR into kirbyup,
really appreciate Your work!
All the best,
Cris

**Comment by jonaskuske** [comment]
I'll look into it later! :) 

(also, Vite 4 compat)

**Comment by jonaskuske** [comment]
> It's probably related to getkirby/kirby#4820 and https://github.com/getkirby/kirby/pull/4884/files.

Yup, that's the culprit. If the components are registered after `vuelidate`, `$vue.$options.components` somehow is empty, which breaks HMR.

If you move `app.use(Components)` up just on line so it happens before `app.use(Vuelidate)`, everything works. I have yet to understand why 🤔

**Comment by CrisGraphics** [comment]
Thanks so much guys and happy new year! 🙏🏼 🎉
