### ISSUE TITLE
Debugging Vue

### ISSUE THREAD

**Issue by youngcut** [johannschopplich/kirbyup#37]
What's your workflow for debugging in the browser? I installed [vue dev](https://devtools.vuejs.org/) but it didn't recognize the components...

**Comment by jonaskuske** [comment]
See https://github.com/getkirby/kirby/issues/4796#issuecomment-1285304129 – Kirby doesn't expose Vue on the page, so you have to add a plugin that globally exposes Vue for the DevTools to work
