### ISSUE TITLE
Missing __file property breaks HMR in beta version

### ISSUE THREAD

**Issue by jonaskuske** [johannschopplich/kirbyup#39]
The newly introduced plugin for [component-cleanup](https://github.com/johannschopplich/kirbyup/blob/6d077bb7033b0b9be1a72a7529b943da92ed95dc/src/node/plugins/component-cleanup.ts) removes the `__file` property from components in both production and development builds. This property is [used by the HMR runtime as component ID](https://github.com/johannschopplich/kirbyup/blob/6d077bb7033b0b9be1a72a7529b943da92ed95dc/src/node/plugins/utils.ts#L59), which is why HMR is broken at the moment.

The reason for the new plugin is that since Vite v4, even production builds contain the debug `__file` property, which should definitely not be published. This is ultimately caused by kirbyup not using Vite's plugin and config system but building its own on top, therefore not giving Vite the chance to handle mode / `NODE_ENV` settings:

kirbyup starts (`NODE_ENV` is *undefined*)
↓
loads Vite config and plugins
↓
`postcss-load-config` [sees that `NODE_ENV` is undefined and sets it to *development*](https://github.com/postcss/postcss-load-config/blob/3f9f537e4eb8e861dde9fd83f52e83886dfdf909/src/index.js#L56)
↓
kirbyup calls `vite.build()`
↓
vite sees that `NODE_ENV` is already set and [does not change it to *production*](https://github.com/vitejs/vite/blob/313712d28893c1e2405f4c2937033873e4c38d7b/packages/vite/src/node/config.ts#L397-L401)
↓
the component compiler emits `__file` props since `NODE_ENV` is *development*

<br>

If kirbyup were a Vite plugin, Vite would load first while `NODE_ENV` was still *undefined*, set it to *production* and then kirbyup would load. So during the whole process `NODE_ENV` would be *production* and `postcss-load-config` would have no reason to mess with the value.

It worked in previous versions as Vite forced `NODE_ENV` to *production* during build in v3, no matter if it was already set or not. So `NODE_ENV` was *undefined* for the first and *development* for the second half of kirbyup's config and setup phase but then set to *production* during the actual build, where the compiler checked whether to emit `__file`. Always was iffy and inconsistent, but fortunately did not cause problems.

The feasible fix (other than turning kirbyup into a Vite plugin and thus giving Vite control over both init/config and build processes) is to set `NODE_ENV` manually to the correct value as kirbyup starts.

**Comment by johannschopplich** [comment]
Hey Jonas, 
thanks for tracking down the source for the error, as well as the in-depth and verbose description!
