### ISSUE TITLE
kirbyup.config.js kills the process without any output

### ISSUE THREAD

**Issue by iskrisis** [johannschopplich/kirbyup#9]
Not sure how to debug this but just existence of `kirbyup.config.js` (or .ts) silently kills the process. 

Happens on `v0.22.2`, `v0.22.1` (on this version there is error which i assume from commit history is unrelated), `v0.22.0`

Both on `node@17.3.1` and `node@16.13.2` 

When i create `vite.config.js` error is thrown. I assume thats reason for `kirbyup.config.js` to exist so you can provision some defaults.

Honestly i just wanted to add sourcemaps to js build (maybe good idea to add to development mode defaults) so i can see correct line numbers with errors/logs in console.

**Comment by johannschopplich** [comment]
Hey there, have you tried the example [provided by the tests](https://github.com/johannschopplich/kirbyup/blob/25c371581f3546cab50dbb120fee4eb17e2f0823/tests/index.test.ts#L107)? Or was your `kirbyup.config.(js|ts)` empty?

I can't follow what you intend or mean by creating a `vite.config.js`. The purpose of the kirbyup configuration file is to give some configuration defaults just like with a Vite config, while keeping the internal Vite config needed for bundling.

**Comment by iskrisis** [comment]
Strangely this happens only with `npx` i've installed the package into the project and the config works. Yes i've tried the config you provided that was first thing i've tried. Even with installed package any error in `kirbyup.config.js` is silent. Not sure this can be solved somehow.

**Comment by johannschopplich** [comment]
I'm using [unconfig](https://github.com/antfu/unconfig) to load config files. This allows me to use TS files in an ESM context. Not sure on how errors are handled within the package or even if I can read them. Good point; probably a task for the future!

I recommend installing kirbyup instead of using npx.

Did you successfully enable source maps tho?
